spring:
  application:
    name: SpringVueWebApp

  jpa:
    show-sql: true
  datasource:
    username: root
    password: 4433
    url: jdbc:mysql://localhost:3306/spring_crud?createDatabaseIfNotExist=true

