spring:
  application:
    name: SpringBootWithAi
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?createDatabaseIfNotExist=true
    username: root
    password: 4433



